import type { CapabilityDescriptor } from "./types.js";
export const builtinCapabilities: readonly CapabilityDescriptor[] = [
{id:"hierarchical-selection",version:"0.1.0",title:"Hierarchical Selection",description:"Select one or more stable identities from hierarchical reference data.",maturity:"candidate",category:"input",useWhen:["The human selects from a hierarchy"],doNotUseWhen:["Business meaning must be inferred from labels"],inputs:["hierarchical-reference","selection-value"],outputs:["selection-change-request"],ownsState:"interaction-only",sideEffects:"request-only",renderers:["web-vnode"],constraints:["Selection is controlled","Business truth stays in the host"]},
{id:"decision-panel",version:"0.1.0",title:"Decision Panel",description:"Focus a human on a bounded decision with evidence, alternatives and consequences.",maturity:"candidate",category:"decision",useWhen:["Human judgment is required"],doNotUseWhen:["The action is safely deterministic"],inputs:["decision-question","alternatives","evidence","impact"],outputs:["decision-request"],ownsState:"interaction-only",sideEffects:"request-only",renderers:["web-vnode","html"],composesWith:["evidence-stack","impact-preview","confirmation"],constraints:["Decision-critical evidence cannot be hidden by personalization"]},
{id:"evidence-stack",version:"0.1.0",title:"Evidence Stack",description:"Present traceable evidence supporting a human decision.",maturity:"candidate",category:"decision",useWhen:["A human needs reasons or supporting facts"],doNotUseWhen:["Evidence is unavailable"],inputs:["evidence-items"],outputs:["evidence-focus"],ownsState:"interaction-only",sideEffects:"none",renderers:["web-vnode","html"],constraints:["Mandatory evidence remains available"]},
{id:"impact-preview",version:"0.1.0",title:"Impact Preview",description:"Show expected consequences before a consequential action.",maturity:"candidate",category:"decision",useWhen:["A decision has non-trivial downstream consequences"],doNotUseWhen:["Consequences cannot be represented responsibly"],inputs:["impact-items"],outputs:["impact-review"],ownsState:"presentation-only",sideEffects:"none",renderers:["web-vnode","html"]},
{id:"exception-queue",version:"0.1.0",title:"Exception Queue",description:"Prioritize anomalies requiring human attention without creating alert noise.",maturity:"candidate",category:"exception",useWhen:["Automation identifies bounded exceptions"],doNotUseWhen:["Every item is treated as an exception"],inputs:["exception-items","attention-semantics"],outputs:["exception-focus","review-request"],ownsState:"interaction-only",sideEffects:"request-only",renderers:["web-vnode","html"],constraints:["Objective importance is separate from presentation preference"]},
{id:"diff-view",version:"0.1.0",title:"Diff View",description:"Explain meaningful change between two states.",maturity:"candidate",category:"decision",useWhen:["A human needs to understand what changed"],doNotUseWhen:["No stable before/after reference exists"],inputs:["before","after","change-semantics"],outputs:["diff-focus"],ownsState:"presentation-only",sideEffects:"none",renderers:["web-vnode","html"]},
{id:"confirmation",version:"0.1.0",title:"Confirmation",description:"Require explicit acknowledgement before a consequential request.",maturity:"candidate",category:"feedback",useWhen:["Consequence warrants acknowledgement"],doNotUseWhen:["Confirmation is repetitive noise"],inputs:["summary","consequences"],outputs:["confirm-request","cancel-request"],ownsState:"interaction-only",sideEffects:"request-only",renderers:["web-vnode","html","mobile"]},
{id:"timeline",version:"0.1.0",title:"Timeline",description:"Present ordered events and transitions with stable temporal reference.",maturity:"candidate",category:"display",useWhen:["Temporal sequence matters"],doNotUseWhen:["Order is not meaningful"],inputs:["timeline-items"],outputs:["timeline-focus"],ownsState:"interaction-only",sideEffects:"none",renderers:["web-vnode","html"]},
{id:"adaptive-layout",version:"0.1.0",title:"Adaptive Layout",description:"Arrange experience regions under explicit stability and policy constraints.",maturity:"candidate",category:"layout",useWhen:["Presentation may adapt to role, task, device or preference"],doNotUseWhen:["Change destroys shared reference or familiarity"],inputs:["regions","experience-context","presentation-constraints"],outputs:["resolved-layout"],ownsState:"presentation-only",sideEffects:"none",renderers:["web-vnode","html","mobile"],constraints:["Adaptation should converge","Invariant regions cannot be freely rearranged"]},
{id:"shared-focus",version:"0.1.0",title:"Shared Focus",description:"Maintain a stable shared reference to what collaborators are reviewing.",maturity:"candidate",category:"collaboration",useWhen:["Multiple humans jointly review the same experience"],doNotUseWhen:["Participants work independently"],inputs:["collaboration-context","focus-reference"],outputs:["shared-focus-request"],ownsState:"interaction-only",sideEffects:"request-only",renderers:["web-vnode","html"],constraints:["Shared identity is stable across participants"]}
] as const;
export function getCapability(id:string):CapabilityDescriptor|undefined{return builtinCapabilities.find(c=>c.id===id);}
export function discoverCapabilities(query:{category?:CapabilityDescriptor["category"];renderer?:string;maturity?:CapabilityDescriptor["maturity"]}):CapabilityDescriptor[]{
  return builtinCapabilities.filter(c=>(!query.category||c.category===query.category)&&(!query.renderer||c.renderers.some(r=>r===query.renderer))&&(!query.maturity||c.maturity===query.maturity));
}
