export type Column={key:string;title:string;width?:number|string;sortable?:boolean;filterable?:boolean;render?:(value:any,record:any)=>any;align?:'left'|'center'|'right';hidden?:boolean};
export type Pagination={page:number;pageSize:number;total:number;pageSizeOptions?:number[]};
export type Sort={field:string;order:'asc'|'desc'}|null;
export type TableAction={key:string;label:string;icon?:string;onClick:(record:any)=>void;permission?:string;visible?:(record:any)=>boolean};
export type FormField={name:string;label:string;type:'text'|'email'|'password'|'number'|'select'|'textarea'|'date'|'custom';placeholder?:string;defaultValue?:any;required?:boolean;rules?:((value:any)=>string|null)[];options?:{label:string;value:any}[];visible?:(values:Record<string,any>)=>boolean;disabled?:(values:Record<string,any>)=>boolean;render?:(props:any)=>any;width?:number|string};
export type FormLayout='vertical'|'horizontal'|'inline';
export type TreeKey=string|number;
export type TreeItem={id:TreeKey;label:string;icon?:string;disabled?:boolean;children?:TreeItem[];[key:string]:unknown};
export type TreeSelectValue=TreeKey|null|TreeKey[];
export type TreeSelectCascade='none'|'descendants';
export type TreeSelectConfig={name:string;data:TreeItem[];valueKey?:string;labelKey?:string;childrenKey?:string;placeholder?:string;searchPlaceholder?:string;multiple?:boolean;checkable?:boolean;searchable?:boolean;disabled?:boolean;cascade?:TreeSelectCascade};
export type TreeSelectState={value:TreeSelectValue;expandedKeys:TreeKey[];open:boolean;search:string;focused:boolean;hovered:boolean};
export type TreeSelectAction='toggle-open'|'toggle-expand'|'select'|'check'|'search'|'focus'|'blur'|'hover'|'leave'|'clear';
export type TreeSelectEvent={name:string;action:TreeSelectAction;key?:TreeKey;value?:unknown};
export interface UploadConfig{name:string;accept?:string;multiple?:boolean;maxSize?:number;autoUpload?:boolean;action?:string;dragDrop?:boolean;maxCount?:number}
export interface DatePickerConfig{name:string;value?:string;format?:string;placeholder?:string;disabled?:boolean;minDate?:string;maxDate?:string;clearable?:boolean}
