import { describe,it,expect,beforeEach } from 'vitest';
import { createStore,createApp,createRouter } from './index';
describe('Eidos core convergence regression',()=>{
 beforeEach(()=>{document.body.innerHTML='<div id="app"></div>';window.location.hash='';});
 it('keyed reorder reuses nodes',()=>{const store=createStore({items:[{id:1,text:'a'},{id:2,text:'b'},{id:3,text:'c'}]});const view=(s:any)=>({type:'div',children:s.items.map((i:any)=>({type:'div',key:i.id,props:{'data-id':String(i.id)},children:[{type:'span',props:{text:i.text}}]}))});createApp({store,view,container:'#app'});const [a,b,c]=document.querySelectorAll('#app > div > div');store.dispatch((p:any)=>({...p,items:[p.items[2],p.items[0],p.items[1]]}),['items']);const r=document.querySelectorAll('#app > div > div');expect(r[0]).toBe(c);expect(r[1]).toBe(a);expect(r[2]).toBe(b);});
 it('event prop updates use new event value',()=>{const store=createStore({event:'OLD'});createApp({store,container:'#app',view:(s:any)=>({type:'button',props:{text:'go',onClick:s.event}})});const seen:string[]=[];window.addEventListener('eidos-event',(e:any)=>seen.push(e.detail.type),{once:false});(document.querySelector('button') as HTMLButtonElement).click();store.dispatch((p:any)=>({...p,event:'NEW'}),['event']);(document.querySelector('button') as HTMLButtonElement).click();expect(seen.slice(-2)).toEqual(['OLD','NEW']);});
 it('boolean properties and onChange are correct',()=>{const store=createStore({checked:false});createApp({store,container:'#app',view:(s:any)=>({type:'input',props:{type:'checkbox',checked:s.checked,disabled:false,onChange:'CHANGED'}})});const input=document.querySelector('input') as HTMLInputElement;expect(input.checked).toBe(false);expect(input.disabled).toBe(false);let detail:any;window.addEventListener('eidos-event',(e:any)=>detail=e.detail,{once:true});input.checked=true;input.dispatchEvent(new Event('change',{bubbles:true}));expect(detail.type).toBe('CHANGED');expect(detail.value).toBe(true);});
 it('app and router expose dispose',()=>{const store=createStore({route:'',params:{}});const app=createApp({store,container:'#app',view:()=>({type:'div'})});const router=createRouter([{path:'/',component:()=>({type:'div'})}],store);expect(typeof app.dispose).toBe('function');expect(typeof router.dispose).toBe('function');app.dispose();router.dispose();});
});
