import type { LocalizationBundleV010 } from "./contracts.js";

export const eidosAppHostLocalizationBundles: LocalizationBundleV010[] = [
  {
    contractVersion: "0.1.0",
    namespace: "eidos.app-host",
    locale: "en",
    messages: {
      "shell.language": "Language",
      "shell.applications": "Applications",
      "shell.noActivePage": "No active application page.",
      "shell.noRoute": "No active route for '{path}'.",
      "shell.noActionHost": "No App Host ActionHost is configured.",
      "shell.executing": "Executing…",
      "shell.completed": "Completed.",
      "shell.next": "Next: {next}",
      "shell.actionFailed": "Action failed: {message}",
      "shell.status": "App Host: {status} · revision {revision}",
      "shell.statusDiagnostics": "App Host: {status} · {count} diagnostic(s)",
      "shell.actionUnavailable": "This action is not available yet.",
      "shell.actionIncomplete": "Catalog command action is incomplete.",
      "shell.confirm": "Confirm action?",
      "shell.assistantUnavailable": "Assistant is not installed or active.",
      "shell.browserAddress": "Workspace address",
      "shell.browserGo": "Open",
      "shell.browserOpenExternal": "Open externally",
      "shell.browserExternalContent": "External web content",
      "shell.browserInvalidTarget": "Enter an App Host route beginning with '/' or an http(s) URL.",
      "shell.mobileMenu": "Menu",
      "shell.mobileChat": "Chat",
      "shell.mobileWorkspace": "Workspace",
      "shell.settingsSaved": "Settings saved.",
      "shell.chatHistory": "Conversation history",
      "shell.chatNew": "New chat",
      "shell.chatArchive": "Archive",
      "shell.chatUntitled": "New chat",
      "shell.chatArchivedLabel": "[Archived] {title}",
      "shell.locale.en": "English",
      "shell.locale.zh-CN": "简体中文",
      "shell.locale.ja": "日本語",
      "shell.locale.zh-TW": "繁體中文",
      "workbench.activityBar": "Activity Bar",
      "workbench.workspaceToolbar": "Workspace toolbar",
      "workbench.workspaceTarget": "Workspace route or web address",
      "workbench.resizeSidePanel": "Resize side panel",
      "workbench.hideSidePanel": "Hide side panel",
      "workbench.showSidePanel": "Show side panel",
      "workbench.status": "{title} · {status}",
      "help.breadcrumb": "Breadcrumb",
      "help.related": "Related",
      "help.owner": "owner: {owner}",
      "help.reviewed": "reviewed: {date}",
      "help.locale": "locale: {locale}",
      "help.kind.start": "Getting started",
      "help.kind.how-to": "How-to",
      "help.kind.concept": "Concept",
      "help.kind.reference": "Reference",
      "help.kind.troubleshooting": "Troubleshooting",
      "help.kind.administration": "Administration",
      "help.kind.development": "Development",
      "help.kind.migration": "Migration",
      "help.audience.user": "User",
      "help.audience.admin": "Admin",
      "help.audience.operator": "Operator",
      "help.audience.support": "Support",
      "help.audience.developer": "Developer",
      "help.audience.agent": "Agent",
      "help.applies.packageVersion": "Package",
      "help.applies.eidosVersion": "Eidos",
      "help.applies.appPlatformVersion": "App Platform"
    }
  },
  {
    contractVersion: "0.1.0",
    namespace: "eidos.app-host",
    locale: "zh-CN",
    messages: {
      "shell.language": "语言",
      "shell.applications": "应用",
      "shell.noActivePage": "当前没有可用的应用页面。",
      "shell.noRoute": "当前路径“{path}”没有可用页面。",
      "shell.noActionHost": "App Host 尚未配置 ActionHost。",
      "shell.executing": "正在执行…",
      "shell.completed": "已完成。",
      "shell.next": "下一步：{next}",
      "shell.actionFailed": "操作失败：{message}",
      "shell.status": "App Host：{status} · 版本 {revision}",
      "shell.statusDiagnostics": "App Host：{status} · {count} 个诊断",
      "shell.actionUnavailable": "此操作当前不可用。",
      "shell.actionIncomplete": "Catalog 命令操作信息不完整。",
      "shell.confirm": "确认执行？",
      "shell.assistantUnavailable": "智能助手尚未安装或启用。",
      "shell.browserAddress": "工作区地址",
      "shell.browserGo": "打开",
      "shell.browserOpenExternal": "外部打开",
      "shell.browserExternalContent": "外部网页内容",
      "shell.browserInvalidTarget": "请输入以“/”开头的 App Host 路径，或 http(s) URL。",
      "shell.mobileMenu": "菜单",
      "shell.mobileChat": "对话",
      "shell.mobileWorkspace": "工作区",
      "shell.settingsSaved": "设置已保存。",
      "shell.chatHistory": "对话历史",
      "shell.chatNew": "新对话",
      "shell.chatArchive": "归档",
      "shell.chatUntitled": "新对话",
      "shell.chatArchivedLabel": "【已归档】{title}",
      "shell.locale.en": "English",
      "shell.locale.zh-CN": "简体中文",
      "shell.locale.ja": "日本語",
      "shell.locale.zh-TW": "繁體中文",
      "workbench.activityBar": "活动栏",
      "workbench.workspaceToolbar": "工作区工具栏",
      "workbench.workspaceTarget": "工作区路径或网页地址",
      "workbench.resizeSidePanel": "调整侧栏宽度",
      "workbench.hideSidePanel": "隐藏侧栏",
      "workbench.showSidePanel": "显示侧栏",
      "workbench.status": "{title} · {status}",
      "help.breadcrumb": "面包屑导航",
      "help.related": "相关内容",
      "help.owner": "所有者：{owner}",
      "help.reviewed": "已复核：{date}",
      "help.locale": "语言：{locale}",
      "help.kind.start": "快速开始",
      "help.kind.how-to": "操作指南",
      "help.kind.concept": "概念",
      "help.kind.reference": "参考",
      "help.kind.troubleshooting": "故障排查",
      "help.kind.administration": "管理",
      "help.kind.development": "开发",
      "help.kind.migration": "迁移",
      "help.audience.user": "用户",
      "help.audience.admin": "管理员",
      "help.audience.operator": "运维",
      "help.audience.support": "支持",
      "help.audience.developer": "开发者",
      "help.audience.agent": "Agent",
      "help.applies.packageVersion": "Package",
      "help.applies.eidosVersion": "Eidos",
      "help.applies.appPlatformVersion": "App Platform"
    }
  },
  {
    contractVersion: "0.1.0",
    namespace: "eidos.app-host",
    locale: "ja",
    messages: {
      "shell.language": "言語",
      "shell.applications": "アプリケーション",
      "shell.noActivePage": "利用可能なアプリケーションページはありません。",
      "shell.noRoute": "現在のパス「{path}」に利用可能なページがありません。",
      "shell.noActionHost": "App Host に ActionHost が設定されていません。",
      "shell.executing": "実行中…",
      "shell.completed": "完了しました。",
      "shell.next": "次へ：{next}",
      "shell.actionFailed": "操作に失敗しました：{message}",
      "shell.status": "App Host：{status} · リビジョン {revision}",
      "shell.statusDiagnostics": "App Host：{status} · 診断 {count} 件",
      "shell.actionUnavailable": "この操作は現在利用できません。",
      "shell.actionIncomplete": "Catalog コマンドの情報が不完全です。",
      "shell.confirm": "操作を実行しますか？",
      "shell.assistantUnavailable": "アシスタントがインストールまたは有効化されていません。",
      "shell.browserAddress": "ワークスペースのアドレス",
      "shell.browserGo": "開く",
      "shell.browserOpenExternal": "外部で開く",
      "shell.browserExternalContent": "外部 Web コンテンツ",
      "shell.browserInvalidTarget": "「/」で始まる App Host パス、または http(s) URL を入力してください。",
      "shell.mobileMenu": "メニュー",
      "shell.mobileChat": "チャット",
      "shell.mobileWorkspace": "ワークスペース",
      "shell.settingsSaved": "設定を保存しました。",
      "shell.chatHistory": "会話履歴",
      "shell.chatNew": "新しいチャット",
      "shell.chatArchive": "アーカイブ",
      "shell.chatUntitled": "新しいチャット",
      "shell.chatArchivedLabel": "【アーカイブ済み】{title}",
      "shell.locale.en": "English",
      "shell.locale.zh-CN": "简体中文",
      "shell.locale.ja": "日本語",
      "shell.locale.zh-TW": "繁體中文",
      "workbench.activityBar": "アクティビティバー",
      "workbench.workspaceToolbar": "ワークスペースツールバー",
      "workbench.workspaceTarget": "ワークスペースのルートまたは Web アドレス",
      "workbench.resizeSidePanel": "サイドパネルの幅を変更",
      "workbench.hideSidePanel": "サイドパネルを隠す",
      "workbench.showSidePanel": "サイドパネルを表示",
      "workbench.status": "{title} · {status}",
      "help.breadcrumb": "パンくず",
      "help.related": "関連",
      "help.owner": "所有者：{owner}",
      "help.reviewed": "確認日：{date}",
      "help.locale": "言語：{locale}",
      "help.kind.start": "はじめに",
      "help.kind.how-to": "操作ガイド",
      "help.kind.concept": "概念",
      "help.kind.reference": "リファレンス",
      "help.kind.troubleshooting": "トラブルシューティング",
      "help.kind.administration": "管理",
      "help.kind.development": "開発",
      "help.kind.migration": "移行",
      "help.audience.user": "ユーザー",
      "help.audience.admin": "管理者",
      "help.audience.operator": "運用担当",
      "help.audience.support": "サポート",
      "help.audience.developer": "開発者",
      "help.audience.agent": "Agent",
      "help.applies.packageVersion": "Package",
      "help.applies.eidosVersion": "Eidos",
      "help.applies.appPlatformVersion": "App Platform"
    }
  },
  {
    contractVersion: "0.1.0",
    namespace: "eidos.app-host",
    locale: "zh-TW",
    messages: {
      "shell.language": "語言",
      "shell.applications": "應用程式",
      "shell.noActivePage": "目前沒有可用的應用程式頁面。",
      "shell.noRoute": "目前路徑「{path}」沒有可用頁面。",
      "shell.noActionHost": "App Host 尚未設定 ActionHost。",
      "shell.executing": "正在執行…",
      "shell.completed": "已完成。",
      "shell.next": "下一步：{next}",
      "shell.actionFailed": "操作失敗：{message}",
      "shell.status": "App Host：{status} · 版本 {revision}",
      "shell.statusDiagnostics": "App Host：{status} · {count} 個診斷",
      "shell.actionUnavailable": "此操作目前不可用。",
      "shell.actionIncomplete": "Catalog 命令操作資訊不完整。",
      "shell.confirm": "確認執行？",
      "shell.assistantUnavailable": "智慧助理尚未安裝或啟用。",
      "shell.browserAddress": "工作區位址",
      "shell.browserGo": "開啟",
      "shell.browserOpenExternal": "在外部開啟",
      "shell.browserExternalContent": "外部網頁內容",
      "shell.browserInvalidTarget": "請輸入以「/」開頭的 App Host 路徑，或 http(s) URL。",
      "shell.mobileMenu": "選單",
      "shell.mobileChat": "對話",
      "shell.mobileWorkspace": "工作區",
      "shell.settingsSaved": "設定已儲存。",
      "shell.chatHistory": "對話記錄",
      "shell.chatNew": "新對話",
      "shell.chatArchive": "封存",
      "shell.chatUntitled": "新對話",
      "shell.chatArchivedLabel": "【已封存】{title}",
      "shell.locale.en": "English",
      "shell.locale.zh-CN": "简体中文",
      "shell.locale.ja": "日本語",
      "shell.locale.zh-TW": "繁體中文",
      "workbench.activityBar": "活動列",
      "workbench.workspaceToolbar": "工作區工具列",
      "workbench.workspaceTarget": "工作區路徑或網頁位址",
      "workbench.resizeSidePanel": "調整側邊欄寬度",
      "workbench.hideSidePanel": "隱藏側邊欄",
      "workbench.showSidePanel": "顯示側邊欄",
      "workbench.status": "{title} · {status}",
      "help.breadcrumb": "麵包屑導覽",
      "help.related": "相關內容",
      "help.owner": "擁有者：{owner}",
      "help.reviewed": "已檢視：{date}",
      "help.locale": "語言：{locale}",
      "help.kind.start": "快速開始",
      "help.kind.how-to": "操作指南",
      "help.kind.concept": "概念",
      "help.kind.reference": "參考",
      "help.kind.troubleshooting": "疑難排解",
      "help.kind.administration": "管理",
      "help.kind.development": "開發",
      "help.kind.migration": "移轉",
      "help.audience.user": "使用者",
      "help.audience.admin": "管理員",
      "help.audience.operator": "維運",
      "help.audience.support": "支援",
      "help.audience.developer": "開發者",
      "help.audience.agent": "Agent",
      "help.applies.packageVersion": "Package",
      "help.applies.eidosVersion": "Eidos",
      "help.applies.appPlatformVersion": "App Platform"
    }
  }
];
