export const treeSelectStyles = {
  container: { position: 'relative' as const, width: '100%', fontFamily: '-apple-system, sans-serif', fontSize: '14px' },
  trigger: { display: 'flex', alignItems: 'center', border: '1px solid #d9d9d9', borderRadius: '4px', padding: '4px 8px', background: '#fff', cursor: 'pointer', minHeight: '32px', justifyContent: 'space-between' as const },
  triggerHover: { borderColor: '#40a9ff' },
  triggerDisabled: { background: '#f5f5f5', cursor: 'not-allowed', color: '#bfbfbf' },
  valueText: { flex: 1, overflow: 'hidden' as const, textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const },
  placeholderText: { color: '#bfbfbf' },
  tags: { display: 'flex', flexWrap: 'wrap' as const, gap: '4px', flex: 1 },
  tag: { display: 'inline-flex', alignItems: 'center', padding: '1px 6px', background: '#f0f0f0', borderRadius: '2px', fontSize: '12px', color: '#333' },
  arrow: { fontSize: '10px', color: '#999', marginLeft: '8px', transition: 'transform 0.2s' },
  arrowOpen: { transform: 'rotate(180deg)' },
  dropdown: { position: 'absolute' as const, top: 'calc(100% + 4px)', left: 0, right: 0, maxHeight: '300px', overflowY: 'auto' as const, background: '#fff', border: '1px solid #d9d9d9', borderRadius: '4px', boxShadow: '0 4px 12px rgba(0,0,0,0.08)', zIndex: 1000, padding: '4px 0' },
  searchInput: { width: '100%', padding: '6px 12px', border: 'none', borderBottom: '1px solid #f0f0f0', outline: 'none', fontSize: '13px', background: 'transparent', boxSizing: 'border-box' as const },
  searchInputFocus: { borderBottomColor: '#40a9ff' },
  nodeRow: { display: 'flex', alignItems: 'center', padding: '4px 8px', borderRadius: '4px', cursor: 'pointer', transition: 'background 0.15s' },
  nodeRowHover: { background: '#f5f5f5' },
  nodeRowSelected: { background: '#e6f7ff' },
  nodeRowDisabled: { cursor: 'not-allowed', opacity: 0.6 },
  toggleIcon: { fontSize: '10px', marginRight: '4px', cursor: 'pointer', color: '#999', width: '16px', display: 'inline-block', textAlign: 'center' as const },
  checkbox: { marginRight: '4px', cursor: 'pointer' },
  nodeLabel: { padding: '2px 4px', borderRadius: '2px', flex: 1 },
  empty: { padding: '16px', color: '#bfbfbf', textAlign: 'center' as const },
};
export const getIndent = (level: number): number => level * 20;
